.ORIG x4000

ST R7, STORE_R7 ;STORE R7
LD R1, NEG_FORTY_EIGHT ; LOAD REGSTER 1 (ASCII CONVERSION)
GETC    ; GET USER INPUT
ST R0, DIGIT_1 ; STORE DIGIT 1 IN REGISTER 0
OUT ; ECHO INPUT

ADD R2, R1, R0 ; ADDING NEG_FORTY_EIGHT

LD R0, TEN
AND R3, R3, #0 ; CLEAROUT R3

MULTIPLY ; start loop
ADD R3, R3, R2
ADD R0, R0, #-1
BRp MULTIPLY

LD R1, NEG_FORTY_EIGHT
GETC
ST R0, DIGIT_2
OUT

ADD R2, R1, R0

ADD R0, R3, R2 ; FULL NUMBER

LD R7, STORE_R7 ; RESTORE ADDRESS
RET

NEG_FORTY_EIGHT .FILL  #-48
DIGIT_1 .BLKW #1
DIGIT_2 .BLKW #1
STORE_R7 .BLKW #1
TEN .FILL #10



.END