.ORIG x3000

MAIN ; MAIN FUNCTION

LEA R0, ENTER_A_NUMBER ; ASK PROMPT
PUTS ; PRINT
GETC ; GET USER INPUT
OUT ; PRINT USER INPUT
LD R1, ASCII_NUM ; LOAD ASCII VALUE OFFSET
ADD R0, R0, R1 ; SUBTRACT OFFSET

ADD R2, R0, #-5 ; SUBTRACT 5
BRn LESS ; IF NUMBER IS NEGATIVE, BRANCH TO LESS LOOP

ADD R2, R0, #-5 ; SUBTRACT 5
BRz EQUAL_TO ; ; IF NUMBER IS ZERO, BRANCH TO EQUAL LOOP

ADD R2, R0, #-5 ; SUBTRACT 5
BRp GREATER ; IF NUMBER IS POSITIVE, BRANCH TO GREAT LOOP

LESS ; LESS THAN 5
LEA R0, SMALLER ; LOAD SMALLER PROMPT
PUTS ; PRINT
BR CONTINUE ; GO TO INFINITE LOOP

EQUAL_TO ; EQUAL TO 5
LEA R0, EQUAL ; LOAD EQUAL PROMPT
PUTS ; PRINT
BR CONTINUE ; GO TO INFINITE LOOP

GREATER ; GREATER THAT 5
LEA R0, LARGER ; LOAD GREATER PROMPT
PUTS ; PRINT
BR CONTINUE ; GO TO INFINITE LOOP


CONTINUE ; INFINITE LOOP
BR MAIN ; GO TO MAIN

HALT ; HALT PROGRAM


ENTER_A_NUMBER .STRINGZ "\nPlease enter a number: "
LARGER .STRINGZ "\nThe number you entered was greater than 5!"
SMALLER .STRINGZ "\nThe number you entered was less than 5!"
EQUAL .STRINGZ "\nThe number you entered was equal to 5!"
ASCII_NUM .FILL #-48
.END
